# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('appid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
                ('application', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('publish_date', models.DateField()),
                ('url', models.CharField(max_length=128)),
                ('desc', models.TextField()),
            ],
        ),
    ]
