# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authorization', '0003_auto_20200620_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='api.APP'),
        ),
    ]
